// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: example_project

#ifndef _EXAMPLE_PROJECT_UI_H
#define _EXAMPLE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Pill_Interval_Label;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_Interval_Hours_Value;
extern lv_obj_t *ui_Interval_Minutes_Value;
extern lv_obj_t *ui_Interval_Seconds_Value;
extern lv_obj_t *ui_Next_Pill_Time_Label;
extern lv_obj_t *ui_Next_Pill_Time_Value;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Image1;
extern lv_obj_t *uic_Pill_Interval_Label;
extern lv_obj_t *uic_Interval_Hours_Value;
extern lv_obj_t *uic_Interval_Minutes_Value;
extern lv_obj_t *uic_Interval_Hours_Value;
extern lv_obj_t *uic_Next_Pill_Time_Label;
extern lv_obj_t *uic_Next_Pill_Time_Value;

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1665093788);   // assets/Pharmachina (Transparent Background).png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
