// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: example_project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, lv_pct(100));
lv_obj_set_height( ui_Container1, lv_pct(100));
lv_obj_set_x( ui_Container1, 0 );
lv_obj_set_y( ui_Container1, 1 );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_Container1);
lv_img_set_src(ui_Image1, &ui_img_1665093788);
lv_obj_set_width( ui_Image1, 300);
lv_obj_set_height( ui_Image1, 53);
lv_obj_set_x( ui_Image1, -74 );
lv_obj_set_y( ui_Image1, -67 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Pill_Interval_Label = lv_label_create(ui_Container1);
lv_obj_set_width( ui_Pill_Interval_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Pill_Interval_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Pill_Interval_Label, -904 );
lv_obj_set_y( ui_Pill_Interval_Label, -134 );
lv_obj_set_align( ui_Pill_Interval_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Pill_Interval_Label,"Pill interval: ");
lv_obj_set_style_text_font(ui_Pill_Interval_Label, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container4 = lv_obj_create(ui_Container1);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_width( ui_Container4, lv_pct(100));
lv_obj_set_height( ui_Container4, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_Container4, 0 );
lv_obj_set_y( ui_Container4, 35 );
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Interval_Hours_Value = lv_label_create(ui_Container4);
lv_obj_set_width( ui_Interval_Hours_Value, 60);
lv_obj_set_height( ui_Interval_Hours_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Interval_Hours_Value, -84 );
lv_obj_set_y( ui_Interval_Hours_Value, -6 );
lv_obj_set_align( ui_Interval_Hours_Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_Interval_Hours_Value,"01Hr");
lv_obj_set_style_text_color(ui_Interval_Hours_Value, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Interval_Hours_Value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Interval_Hours_Value, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Interval_Minutes_Value = lv_label_create(ui_Container4);
lv_obj_set_width( ui_Interval_Minutes_Value, 80);
lv_obj_set_height( ui_Interval_Minutes_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Interval_Minutes_Value, -84 );
lv_obj_set_y( ui_Interval_Minutes_Value, -5 );
lv_obj_set_align( ui_Interval_Minutes_Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_Interval_Minutes_Value,"05Min");
lv_obj_set_style_text_color(ui_Interval_Minutes_Value, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Interval_Minutes_Value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Interval_Minutes_Value, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Interval_Seconds_Value = lv_label_create(ui_Container4);
lv_obj_set_width( ui_Interval_Seconds_Value, 70);
lv_obj_set_height( ui_Interval_Seconds_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Interval_Seconds_Value, -84 );
lv_obj_set_y( ui_Interval_Seconds_Value, -6 );
lv_obj_set_align( ui_Interval_Seconds_Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_Interval_Seconds_Value,"05Sec");
lv_obj_set_style_text_color(ui_Interval_Seconds_Value, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Interval_Seconds_Value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Interval_Seconds_Value, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Next_Pill_Time_Label = lv_label_create(ui_Container1);
lv_obj_set_width( ui_Next_Pill_Time_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Next_Pill_Time_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Next_Pill_Time_Label, -904 );
lv_obj_set_y( ui_Next_Pill_Time_Label, -134 );
lv_obj_set_align( ui_Next_Pill_Time_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Next_Pill_Time_Label,"Next pill in:");
lv_obj_set_style_text_font(ui_Next_Pill_Time_Label, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Next_Pill_Time_Value = lv_label_create(ui_Container1);
lv_obj_set_width( ui_Next_Pill_Time_Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Next_Pill_Time_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Next_Pill_Time_Value, -904 );
lv_obj_set_y( ui_Next_Pill_Time_Value, -134 );
lv_obj_set_align( ui_Next_Pill_Time_Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_Next_Pill_Time_Value,"7:45:21");
lv_obj_set_style_text_font(ui_Next_Pill_Time_Value, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

uic_Image1 = ui_Image1;
uic_Pill_Interval_Label = ui_Pill_Interval_Label;
uic_Interval_Hours_Value = ui_Interval_Hours_Value;
uic_Interval_Minutes_Value = ui_Interval_Minutes_Value;
uic_Interval_Hours_Value = ui_Interval_Seconds_Value;
uic_Next_Pill_Time_Label = ui_Next_Pill_Time_Label;
uic_Next_Pill_Time_Value = ui_Next_Pill_Time_Value;

}
